### ISSUE TITLE
PvPManager Running on 1.8.8

### ISSUE THREAD

**Issue by KidFuras** [NoChanceSD/PvPManager-Issues#18] opened 2015-12-05 04:01 UTC
So i just bought your plugin today and most things work great on it except for the AutoRespawn and the When someone in pvp gets tagged by another player his/her name does not turn red I have installed TagApi to resolve it but still no success.

Edit: Still no AutoRespawn but occasionally a players name will turn red but it is very weird how it randomly changes. when i turn on the setting for only attacker to turn red, When player A hits player B, Player A turns red. But when player B hits player A back the red is then transferred from B ->A. If the setting for only Attacker turns red is off then both Players remain white please fix

**Comment by NoChanceSD** [comment] 2015-12-05 23:40
Which version are you using? There is no option for only attacker anymore.

**Comment by KidFuras** [comment] 2015-12-06 04:20
I am using craftbukkit 1.8.8 and the most recent update of your plugin the for only attacker was removed from the config I see but the problem has not changed or been fixed

**Comment by NoChanceSD** [comment] 2015-12-06 18:17
Check if latest update fix any of your issues please. If not, try to check you server log for errors and paste them here.

**Comment by KidFuras** [comment] 2015-12-06 18:19
Will do

**Comment by KidFuras** [comment] 2015-12-06 18:23
I will have a response for you tonight on if it works or not currently at work

**Comment by KidFuras** [comment] 2015-12-08 00:49
Still not fixed when a red player is hit his name is changed back to white

**Comment by NoChanceSD** [comment] 2015-12-13 11:42
Check v3.3.9 please

**Comment by KidFuras** [comment] 2015-12-15 18:08
The Problem still stands it seems to be more accurate when player a hits player b the name is red immediately so gratz there but when player b hits player a(who has a red name), player b does not get a red name and player a( who was initially red) gets a white name also.

**Comment by NoChanceSD** [comment] 2016-02-04 22:31
It has been a while but... i can't reproduce this issue, which other plugins messing with scoreboards do you use?

**Comment by NoChanceSD** [comment] 2016-03-23 23:20
Closing

**Closed by NoChanceSD** 2016-03-23 23:20 UTC
